DWAPlannerROS:
  xy_goal_tolerance: 0.12
  yaw_goal_tolerance: 0.1

  path_distance_bias: 100.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  forward_point_distance: 0.2
  publish_cost_grid_pc: true
  publish_traj_pc: true

  max_trans_vel: 2.0
  min_trans_vel: 0.01
  max_vel_x: 2.0
  min_vel_x: -2.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_rot_vel: 2.0
  min_rot_vel: 0.01
  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_theta: 2.5
  acc_limit_trans: 5.0
  sim_time: 1.5
  sim_granularity: 0.05
  global_frame_id: "map"
  vx_samples: 10
  vy_samples: 1
  vth_samples: 10
  oscillation_reset_angle: 0.01
  valid_trajectory_ratio: 0.0
  max_opposite_angle: 2.35619445

  cheat_factor: 25.0
latch_xy_goal_tolerance: true

